; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

; Serial Monitor options
monitor_speed = 115200

monitor_filters = esp8266_exception_decoder

; Build options
build_flags =

; Source filter to include all source files
build_src_filter = +<*> -<.git/> -<.svn/>
    -D CORE_DEBUG_LEVEL=3

; Library dependencies
lib_deps =
    makuna/NeoPixelBus @ ^2.8.4
    U8g2
    ArduinoJson @ ^6.21.3
    ESP8266HTTPClient
    sparkfun/SparkFun Indoor Air Quality Sensor - ENS160
    sparkfun/SparkFun Qwiic Humidity AHT20

; LittleFS Filesystem
board_build.filesystem = littlefs

; Pre-build script to compress HTML files
extra_scripts = scripts/fs_pipeline.py
